default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  timeout: 5000

development:
  <<: *default
  database: cultural_match_development
test:
  <<: *default
  database: cultural_match_test

production:
  <<: *default
  database: cultural_match_production
  username: cultural_match
  password: <%= ENV["CULTURE_MATCH_DATABASE_PASSWORD"] %>
