default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  timeout: 5000

development:
  <<: *default
  database: cm_development
test:
  <<: *default
  database: cm_test

production:
  <<: *default
  database: cm_production
  username: cm
  password: <%= ENV["CM_DATABASE_PASSWORD"] %>
